version: "3"

services:

    rabbitmq:
        image: rabbitmq:3.7-management
        ports:
            - "127.0.0.1:$RABBITMQ_PORT:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_VHOST: $RABBITMQ_VHOST
            RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
            RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASS
        volumes:
            - ./docker/volumes/rabbitmq:/var/lib/rabbitmq
        restart: always

    redis:
        image: redis:3.2.11-alpine
        ports:
            - "127.0.0.1:$REDIS_PORT:6378"
        volumes:
            - ./docker/volumes/redis:/data

    db:
        image: postgres:11-alpine
        environment:
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_DB: $POSTGRES_DB
            POSTGRES_HOST: db
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - "$POSTGRES_PORT:5432"
        restart: always

volumes:
    db:
        driver: local